# Generated by Django 2.0.4 on 2018-04-25 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('hashPassword', models.CharField(max_length=300)),
                ('email_authenticated', models.BooleanField()),
            ],
        ),
    ]
